name: cyberwow
description: A new Flutter project.

version: 0.7.0+23

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.1.0
  http: ^0.12.0
  logging: ^0.11.3
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - native/output/x86_64/wownerod
   - native/output/arm64/wownerod
   - assets/wownero_symbol.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: VT323
      fonts:
        - asset: fonts/VT323/VT323-Regular.ttf
